# Generated by Django 4.0.4 on 2022-04-24 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Udalost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev_akce', models.CharField(max_length=45, verbose_name='Název akce')),
                ('datum_akce', models.DateField(verbose_name='Datum začátku akce')),
                ('misto_konani', models.CharField(max_length=45, verbose_name='Místo konání akce')),
                ('informace', models.TextField(verbose_name='Informace o události')),
            ],
            options={
                'ordering': ['nazev_akce'],
            },
        ),
        migrations.CreateModel(
            name='Sporty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev_sportu', models.CharField(max_length=45, verbose_name='Název sportu')),
                ('obdobi', models.CharField(choices=[('jaro', 'Jaro'), ('leto', 'Léto'), ('podzim', 'Podzim'), ('zima', 'Zima')], max_length=10, verbose_name='Roční období')),
                ('zeme_puvod_sportu_zkratka', models.CharField(max_length=5, verbose_name='Země průvodu zkratka')),
                ('historie', models.TextField(verbose_name='Historie sportu')),
                ('udalosti', models.ManyToManyField(to='sports.udalost', verbose_name='Událost')),
            ],
            options={
                'ordering': ['nazev_sportu'],
            },
        ),
        migrations.CreateModel(
            name='Hvezdy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=30, verbose_name='Jméno hvězdy')),
                ('prijmeni', models.CharField(max_length=30, verbose_name='Příjmení hvězdy')),
                ('narozeni', models.DateField(verbose_name='Datum narození hvězdy')),
                ('pocet_medaili', models.IntegerField(verbose_name='Počet získaných medailí')),
                ('pohlavi', models.CharField(choices=[('zena', 'Žena'), ('muz', 'Muž'), ('jine', 'Jiné')], max_length=5, verbose_name='Pohlaví')),
                ('kariera', models.TextField(verbose_name='Kariéra')),
                ('sport_nazev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.sporty', verbose_name='Sport')),
            ],
            options={
                'ordering': ['prijmeni', 'jmeno'],
            },
        ),
    ]
