# Generated by Django 4.0.4 on 2022-06-07 16:48

from django.db import migrations, models
import sports.models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_remove_sporty_zeme_puvod_sportu_zkratka_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sporty',
            name='obrazek',
            field=models.ImageField(blank=True, null=True, upload_to=sports.models.sportPath, verbose_name='Obrázky'),
        ),
    ]
